apply from: rootProject.file('gradle/versioning.gradle')

buildscript {
    // Runtime stdlib stays on the last 1.9.x stable so published artifacts do
    // not depend on a Kotlin 2.4 RC. The Gradle plugin is upgraded separately
    // to pick up the CVE-2026-53914 build-cache deserialization fix.
    ext.kotlin_version = '1.9.25'
    // 2.4.20-RC3 is the newest release that includes the CVE-2026-53914 fix.
    // 2.4.10 and earlier remain affected; stable 2.4.20 is not published yet.
    ext.kotlin_plugin_version = '2.4.20-RC3'
  repositories {
  mavenCentral()
  google()
  maven {
    url 'https://plugins.gradle.org/m2/'
  }
}

  dependencies {
    classpath 'com.android.tools.build:gradle:8.7.3'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_plugin_version"
    classpath 'com.vanniktech:gradle-maven-publish-plugin:0.35.0'
  }
}



allprojects {
  buildscript {
    repositories {
      mavenCentral()
      google()
    }
  }

  apply plugin: 'idea'

  repositories {
    mavenCentral()
    google()
  }

  group = GROUP
  version = getVersionName()
}


ext {
  versionCode = Integer.parseInt(VERSION_CODE)
  versionName = getVersionName()

  minSdkVersion = 14
  minSdkVersionWear = 23
  targetSdkVersion = 34
  compileSdkVersion = 34

  sourceCompatibilityVersion = JavaVersion.VERSION_1_8
  targetCompatibilityVersion = JavaVersion.VERSION_1_8
}

ext.deps = [
  supportAnnotations: 'androidx.annotation:annotation:1.1.0'
]
