apply from: rootProject.file('gradle/versioning.gradle')

buildscript {
    ext.kotlin_version = '1.9.25'
  repositories {
  mavenCentral()
  google()
  maven {
    url 'https://plugins.gradle.org/m2/'
  }
}

  dependencies {
    classpath 'com.android.tools.build:gradle:8.7.3'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  }
}



allprojects {
  buildscript {
    repositories {
      mavenCentral()
      google()
    }
  }

  apply plugin: 'idea'

  repositories {
    mavenCentral()
    google()
  }

  group = GROUP
  version = getVersionName()
}


ext {
  versionCode = Integer.parseInt(VERSION_CODE)
  versionName = getVersionName()

  minSdkVersion = 14
  minSdkVersionWear = 23
  targetSdkVersion = 34
  compileSdkVersion = 34

  sourceCompatibilityVersion = JavaVersion.VERSION_1_8
  targetCompatibilityVersion = JavaVersion.VERSION_1_8
}

ext.deps = [
  supportAnnotations: 'androidx.annotation:annotation:1.1.0'
]

//apply from: rootProject.file('gradle/promote.gradle')